### ISSUE TITLE
大佬、这是什么问题？有办法解决吗？

### ISSUE THREAD

**Issue by guyingd** [JACK-ZHANG-coming/my-now-blog#1]
输入yarn start后报错

`Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at BulkUpdateDecorator.hashFactory (D:\my-now-blog\node_modules\webpack\lib\util\createHash.js:144:18)
    at BulkUpdateDecorator.update (D:\my-now-blog\node_modules\webpack\lib\util\createHash.js:46:50)
    at OriginalSource.updateHash (D:\my-now-blog\node_modules\webpack\node_modules\webpack-sources\lib\OriginalSource.js:104:8)
    at NormalModule._initBuildHash (D:\my-now-blog\node_modules\webpack\lib\NormalModule.js:853:17)
    at runCallbacks (D:\my-now-blog\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:27:15)
    at D:\my-now-blog\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:200:4
    at D:\my-now-blog\node_modules\webpack\node_modules\graceful-fs\graceful-fs.js:123:16 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.1.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Comment by JACK-ZHANG-coming** [comment]
重新拉取最新代码试试呢
